name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: zip built files
      run: zip -r TaskList.zip dist
